on:
  push:
  workflow_dispatch:

name: update-docs

jobs:
  update-docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1

      - name: Update db
        id: dbupdate
        run: |
          echo "::set-output name=packs::$(Rscript -e 'cat(remotedocs::extract_repo_database("ropensci", 5)$packs)')"
          echo "::set-output name=update::$(Rscript -e 'cat(remotedocs::extract_repo_database("ropensci", 5)$update)')"
          
      - uses: r-lib/actions/setup-r-dependencies@v1
        name: New dependencies
        if: steps.dbupdate.outputs.packs == TRUE
        with:
          extra-packages: ${{ steps.dbupdate.outputs.packs }}
          needs: website

          
          
          

